app/main/__init__.py
from .views import main

app/main/views.py
from flask import (render_template, Blueprint, current_app, request, abort)
from flask_login import login_required, current_user
from sqlalchemy import desc, func, and_
from .logger import logger
from ..models import Article, Tag, ArticleTag, db, User, Following
from ..utility import exceptionHandler


main = Blueprint('main', __name__, template_folder="templates")


@main.route('/')
@exceptionHandler(logger, 'failed to visit homepage')
def index():
    pageNoStr = request.args.get('pageNo')
    pageNo = int(pageNoStr) if pageNoStr else 1
    pagination = (Article.query.filter(Article.deleted == False).
                  order_by(desc(Article.creationDate)).
                  paginate(pageNo,
                           current_app.config['ARTICLE_COUNT_PER_PAGE'],
                           False))
    return render_template('main/index.html', pagination=pagination,
                           hotTagRecords=Tag.
                           getHotTagRecords(current_app.config['HOT_TAG_COUNT']))


@main.route('/subscriptions')
@login_required
@exceptionHandler(logger, "failed to get subscriptions")
def subscriptions():
    # subscription 订阅
    try:
        pageNo = int(request.args.get('pageNo') or 1)
    except:
        abort(400)

    followedUserIdsQuery = (db.session.query(Following.userId).
                            filter(Following.followerId == current_user.id))
    followedCount = followedUserIdsQuery.count()

    pagination = None
    if followedCount:
        pagination = (db.session.query(Article).
                      filter(and_(Article.deleted == False,
                                  Article.userId.in_(followedUserIdsQuery))).
                      order_by(desc(Article.creationDate)).
                      paginate(pageNo,
                               current_app.config['ARTICLE_COUNT_PER_PAGE'],
                               False))
    return render_template('main/subscriptions.html',
                           followedCount=followedCount,
                           pagination=pagination)


@main.route('/concernedTags')
@login_required
@exceptionHandler(logger, 'failed to visit /concernedTags')
def concernedTags():
    concernedTags = current_user.concernedTags.all()
    if concernedTags:
        try:
            tagId = int(request.args.get('tagId') or concernedTags[0].id)
            pageNo = int(request.args.get('pageNo') or 1)
            if tagId not in (tag.id for tag in concernedTags):
                raise ValueError("{} didn't concerned tag {}".
                                 format(current_user, tagId))
        except:
            abort(400)

    stmt = Tag.query.get(tagId).articleRecords.subquery()
    pagination = (Article.query.filter(Article.deleted == False).
                  join(stmt, stmt.c.articleId == Article.id).
                  order_by(desc(Article.creationDate)).
                  paginate(pageNo,
                           current_app.config['ARTICLE_COUNT_PER_PAGE'],
                           False))

    return render_template('main/concernedTags.html', currentTagId=tagId,
                           concernedTags=concernedTags, pagination=pagination)


@main.route('/showTag/<int:tagId>')
@exceptionHandler(logger, 'failed to show tag')
def showTag(tagId):
    tag = Tag.query.get_or_404(tagId)
    try:
        pageNo = int(request.args.get('pageNo') or 1)
    except:
        abort(400)

    order = (desc(Article.viewedCount) if request.args.get('hot')
             else desc(Article.creationDate))

    articleIdsQuery = (db.session.query(ArticleTag.articleId).
                       filter(ArticleTag.tagId == tag.id).subquery())
    pagination = (Article.query.filter(Article.deleted == False).
                  join(articleIdsQuery, Article.id == articleIdsQuery.c.articleId).
                  order_by(order).order_by(desc(Article.creationDate)).
                  paginate(pageNo, current_app.config['ARTICLE_COUNT_PER_PAGE']))

    stmt = db.session.query(ArticleTag.articleId).filter(ArticleTag.tagId == tag.id).subquery()
    stmt2 = (db.session.query(Article.userId, func.count(Article.id).label('count')).
             filter(Article.deleted == False).
             join(stmt, stmt.c.articleId == Article.id).
             group_by(Article.userId).order_by(desc(func.count(Article.id))).
             limit(current_app.config['FAMOUS_USER_COUNT'])).subquery()
    famousUserRecords = (db.session.query(User, stmt2.c.count).
                         join(stmt2, User.id == stmt2.c.userId).
                         order_by(desc(stmt2.c.count)).all())

    return render_template('main/showTag.html', tag=tag,
                           pagination=pagination,
                           famousUserRecords=famousUserRecords)

app/templates/main/concernedTags.html
{% extends "layoutMainLeft.html" %}
{% from "macros/utility.html" import renderPagination, renderFlashedMessages, renderArticle, renderUserInfo %}


{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/renderArticle.css') }}" rel="stylesheet"/>
<link href="{{ url_for('static', filename='css/main/concernedTags.css') }}" rel="stylesheet"/>
{% endblock css %}


{% block title %}Blog-主题{% endblock title %}


{% block themeActived %}class="active"{% endblock themeActived %}


{% block main %}

{% if not concernedTags %}
<div class="box-3d">
    <h4>您还未关注任何主题，<a href="{{ url_for('main.index') }}"><small>去逛逛？</small></a></h4>
</div>

{% else %}


<div class="tag-category-container">
    <h4>您已关注的主题：</h4>
    <ul class="tag-category">
        {% for tag in current_user.concernedTags.all() %}
        {% if tag.id != currentTagId %}
        <li>
            <a href="{{ url_for('main.concernedTags', tagId=tag.id) }}">{{ tag.name }}</a>
        </li>
        {% else %}
        <li class="active">
            <a href="#">{{ tag.name }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>


{% if not pagination or not pagination.items %}

<div id="box-3d">
    <h4>并没有相关文章。。。</h4>
</div>

{% else %}

{% for article in pagination.items %}
{{ renderArticle(article) }}
{% endfor %}

<div id="pagination">
    <center>
        {{ renderPagination(pagination, 'main.concernedTags', tagId=currentTagId) }}
    </center>
</div>

{% endif %}

{% endif %}

{% endblock main %}


{% block extra %}

{% if current_user.is_authenticated %}
{{ renderUserInfo(current_user) }}
{% else %}
<h4 class="text-center">您还未登录</h4>
{% endif %}

{% endblock extra %}

app/templates/main/index.html
{% extends "layoutMainLeft.html" %}
{% from "macros/utility.html" import renderPagination, renderArticle %}


{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/renderArticle.css') }}" rel="stylesheet"/>
{% endblock css %}


{% block title %}Blog-首页{% endblock title %}


{% block homeActived %}class="active"{% endblock homeActived %}


{% block main %}

{{ renderFlashedMessages('warning') }}

{% if pagination and pagination.items %}

{% for article in pagination.items %}
{{ renderArticle(article) }}
{% endfor %}

<div id="pagination">
    <center>
        {{ renderPagination(pagination, 'main.index') }}
    </center>
</div>

{% else %}

<div class="box-3d">
    <h4>网站初上，暂时没有任何文章。。。</h4>
</div>

{% endif %}

{% endblock main %}


{% block extra %}

{% if hotTagRecords %}

<h5>热门主题：</h5>

<ul class="list-group">
    {% for tag, count in hotTagRecords %}
    <li class="list-group-item">
        <span class="badge">{{ count }}</span>{{ tag.name }}
    </li>
    {% endfor %}
</ul>

{% else %}

<h5>暂时没有任何主题</h5>

{% endif %}

{% endblock extra %}

app/templates/main/showTag.html
{% extends "layoutMainLeft.html" %}
{% from "macros/utility.html" import renderPagination, renderArticle, renderUserInfo, renderFamousUserRecords %}


{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/renderArticle.css') }}" rel="stylesheet"/>
<link href="{{ url_for('static', filename='css/main/showTag.css') }}" rel="stylesheet"/>
{% endblock css %}


{% block title %}Blog-主题{% endblock title %}


{% block themeActived %}class="active"{% endblock themeActived %}


{% block main %}

<div class="tag-info">
    <h4>{{ tag.name }}</h4>

    <div>
        <ul>
            {% if not request.args.get('hot') %}
            <li>动态</li>
            <li><a href="{{ url_for('main.showTag', tagId=tag.id, hot=1) }}">热门</a></li>
            {% else %}
            <li><a href="{{ url_for('main.showTag', tagId=tag.id) }}">动态</a></li>
            <li>热门</li>
            {% endif %}
        </ul>

        <a class="btn btn-primary btn-sm pull-right" href="#" style="display:inline-block">关注主题</a>
    </div>
</div>

{% if not pagination or not pagination.items %}
<div class="no-article-info">
    <h4>并没有相关文章。。。</h4>
</div>
{% else %}

{% for article in pagination.items %}
{{ renderArticle(article) }}
{% endfor %}

<div id="pagination">
    <center>
        {{ renderPagination(pagination, 'main.showTag', tagId=tag.id) }}
    </center>
</div>

{% endif %}

{% endblock main %}


{% block extra %}
{{ renderFamousUserRecords(famousUserRecords) }}
{% endblock extra %}

app/templates/main/subscriptions.html
{% extends "layoutMainLeft.html" %}
{% from "macros/utility.html" import renderPagination, renderArticle, renderUserInfo %}


{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/renderArticle.css') }}" rel="stylesheet"/>
<link href="{{ url_for('static', filename='css/main/subscriptions.css') }}" rel="stylesheet"/>
{% endblock css %}


{% block title %}Blog-关注{% endblock title %}


{% block subscriptionsActived %}class="active"{% endblock subscriptionsActived %}


{% block main %}

{% if not followedCount %}
<div id="box-3d">
    <h4>您还未关注任何人，<a href="{{ url_for('main.index') }}"><small>去逛逛？</small></a></h4>
</div>
{% elif not pagination or not pagination.items %}

<div id ="box-3d">
    <h4>您已关注{{ followedCount }}人，但并没有文章...<small><a href="{{ url_for('main.index') }}">去逛逛？</a></small></h4>
</div>

{% else %}

<div id="summary-block">
    <span class="label label-info font-size-lg padding-sm">已关注 <span class="badge">{{ current_user.followedRecords.count() }}</span></span>
    <span class="label label-info font-size-lg padding-sm">文章 <span class="badge">{{ current_user.getFollowedArticleCount() }}</span></span>
</div>

{% for article in pagination.items %}
{{ renderArticle(article) }}
{% endfor %}

<div id="pagination">
    <center>
        {{ renderPagination(pagination, 'main.subscriptions') }}
    </center>
</div>

{% endif %}

{% endblock main %}


{% block extra %}
{% if current_user.is_authenticated %}
{{ renderUserInfo(current_user) }}
{% else %}
<h4 class="text-center">您还未登录</h4>
{% endif %}
{% endblock extra %}

app/templates/main/tag.html
{% extends "base.html" %}
{% from "macros/utility.html" import renderPagination, renderFlashedMessages, renderArticle, renderUserInfo %}

{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/main/base.css') }}" rel="stylesheet"/>
{% endblock css %}

{% block title %}Blog-主题{% endblock title %}


{% block subscriptionsActived %}class="active"{% endblock subscriptionsActived %}


{% block content %}
    <div class="container">
        <div class="row">

            <div class="col-sm-9">

                {{ renderFlashedMessages('warning') }}

                {% if not concernedTags %}
                <div id="not-follow-info">
                    <h4>您还未关注任何主题，<a href="{{ url_for('main.index') }}"><small>去逛逛？</small></a></h4>
                </div>

                {% else %}


                <div class="tag-category-container">
                    <h4>您已关注的主题：</h4>
                    <ul class="tag-category">
                        {% for tag in current_user.concernedTags.all() %}
                        {% if tag.id != currentTagId %}
                        <li>
                            <a href="{{ url_for('main.concernedTags', tagId=tag.id) }}">{{ tag.name }}</a>
                        </li>
                        {% else %}
                        <li class="active">
                            <a href="#">{{ tag.name }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>


                {% if not pagination or not pagination.items %}

                <div id="no-article-info">
                    <h4>并没有相关文章。。。</h4>
                </div>

                {% else %}

                {% for article in pagination.items %}
                {{ renderArticle(article) }}
                {% endfor %}

                <div id="pagination">
                    <center>
                        {{ renderPagination(pagination, 'main.concernedTags', tagId=currentTagId) }}
                    </center>
                </div>

                {% endif %}

                {% endif %}

            </div>

            <div id="extra-info" class="col-sm-3">
                {% if current_user.is_authenticated %}
                {{ renderUserInfo(current_user) }}
                {% else %}
                <h4 class="text-center">您还未登录</h4>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock content %}