app/user/forms.py
from flask_wtf import FlaskForm as Form
from flask_login import current_user
from wtforms import (StringField, PasswordField, ValidationError,
                     FileField, SubmitField)
from wtforms.validators import DataRequired, Length, EqualTo


class BaseInfoForm(Form):
    profilePicture = FileField('头像')
    name = StringField('昵称', validators=[DataRequired(), Length(1, 16)])
    introduction = StringField('简介')
    submit = SubmitField('确认修改')


class PasswordForm(Form):
    password = PasswordField('密码', validators=[DataRequired(), Length(1, 16)])
    newPassword = PasswordField('新密码',
                                validators=[DataRequired(), Length(6, 32)])
    confirm = PasswordField('密码确认',
                            validators=[DataRequired(),
                                        EqualTo('password',
                                                message='两次输入的密码必须相同')])
    submit = SubmitField('确认修改')

    def validate_password(form, field):
        """

        检查原始密码是否输入正确

        """
        if field.data and (not current_user.checkPassword(field.data)):
            raise ValidationError('密码有误!')

app/user/__init__.py
from .views import user

app/user/views.py
from os import path
from flask import (Blueprint, render_template, redirect, url_for,
                   request, current_app, abort, flash)
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from sqlalchemy import func
from ..utility import exceptionHandler
from ..models import db, User, Tag, Article, ArticleTag
from .logger import logger
from .forms import BaseInfoForm, PasswordForm


user = Blueprint('user', __name__, template_folder='templates')


@user.route('/homepage/<int:userId>')
@exceptionHandler(logger, "can't access to user homepage")
def home(userId):
    """

    用户主页，是否登录均可访问

    """
    pageNoStr = request.args.get('pageNo')
    try:
        pageNo = int(pageNoStr) if pageNoStr else 1
    except:
        abort(400)

    user = User.query.get_or_404(userId)

    articleIds = db.session.query(Article.id).filter(Article.userId == user.id)
    stmt = (db.session.query(ArticleTag.tagId, func.count('*').
                             label('count')).
            filter(ArticleTag.articleId.in_(articleIds)).
            group_by(ArticleTag.tagId).subquery())
    tagRecords = (db.session.query(Tag, stmt.c.count).
                  join(stmt, Tag.id == stmt.c.tagId).
                  order_by(Tag.name).
                  all())

    tagIdStr = request.args.get('tagId')
    if tagIdStr:
        try:
            tagId = int(tagIdStr)
        except:
            abort(400)
        if tagId not in (tag.id for tag, _ in tagRecords):
            abort(400)
        pagination = (user.articles.filter(Article.tagId == tagId).
                      order_by(Article.creationDate).
                      paginate(pageNo,
                               current_app.config['ARTICLE_COUNT_PER_PAGE']),
                      False)
    else:
        tagId = None
        pagination = (user.articles.
                      order_by(Article.creationDate).
                      paginate(pageNo,
                               current_app.config['ARTICLE_COUNT_PER_PAGE'],
                               False))

    return render_template('user/home.html', user=user,
                           totalArticleCount=user.articles.count(),
                           pagination=pagination, tagId=tagId, join=path.join,
                           current_app=current_app, tagRecords=tagRecords)


@user.route('/setting')
@login_required
@exceptionHandler(logger, "can't access to user setting")
def setting():
    """

    用户设置个人信息

    """
    return redirect(url_for('.setBaseInfo'))


@user.route('/setBaseInfo', methods=['GET', 'POST'])
@login_required
@exceptionHandler(logger, "can't access to set base info")
def setBaseInfo():
    baseInfoForm = BaseInfoForm()
    if baseInfoForm.validate_on_submit():
        if baseInfoForm.profilePicture.data:
            imageFile = baseInfoForm.profilePicture.data
            uploadedFilename = secure_filename(imageFile.filename)
            filename = (path.
                        join('app/static',
                             current_app.
                             config['USER_PROFILE_PICTURE_SAVE_DIR'],
                             str(current_user.id)
                             + uploadedFilename[uploadedFilename.rfind('.'):]))
            imageFile.save(filename)
            current_user.profilePicture = filename
        if baseInfoForm.name.data:
            current_user.name = baseInfoForm.name.data
        if baseInfoForm.introduction.data:
            current_user.introduction = baseInfoForm.introduction.data
        db.session.add(current_user)
        db.session.commit()
        flash('修改成功')
    else:
        baseInfoForm.name.data = current_user.name
        baseInfoForm.introduction.data = current_user.introduction
    return render_template('user/setting.html', baseInfoForm=baseInfoForm)


@user.route('/setPassword', methods=['GET', 'POST'])
@login_required
@exceptionHandler(logger, "can't access to set password")
def setPassword():
    passwordForm = PasswordForm()
    if passwordForm.validate_on_submit():
        current_user.password = passwordForm.newPassword.data
        db.session.add(current_user)
        db.session.commit()
        flash('修改成功')
    return render_template('user/setting.html', passwordForm=passwordForm)


@user.route('/manage')
@login_required
@exceptionHandler(logger, "can't access to user manage articles")
def manage():
    """

    用户管理文章

    """
    pass

app/templates/user/home.html
{% extends "layoutExtraLeft.html" %}
{% from "macros/utility.html" import renderArticleSimple, renderPagination %}


{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/renderArticleSimple.css') }}" rel="stylesheet"/>
<link href="{{ url_for('static', filename='css/user/home.css') }}" rel="stylesheet"/>
{% endblock css %}


{% block title %}{{ user.name }}的主页{% endblock title %}


{% block extra %}
<div class="user-info">
    <img id="user-picture" class="img img-responsive img-rounded center-block" src="{% if user.profilePicture %}{{ url_for('static', filename=join(current_app.config['USER_PROFILE_PICTURE_SAVE_DIR'], user.profilePicture)) }}{% else %}{{ url_for('static', filename=join(current_app.config['USER_PROFILE_PICTURE_SAVE_DIR'], 'default.jpg')) }}{% endif %}"/>
    <h5 class="user-name">{{ user.name }}</h5>
    <a class="btn btn-primary btn-sm pull-right"><span class="glyphicon glyphicon-plus">加关注</a>
</div>

<div class="user-article-tags">
    <ul class="list-group list-group-sm">
        <a class="list-group-item {% if not tagId %}active{% endif %}">
            <span class="badge">{{ totalArticleCount }}</span>所有文章
        </a>
        {% if not tagId %}

        {% for tag, count in tagRecords %}
        <a class="list-group-item">
            <span class="badge">{{ count }}</span>{{ tag.name }}
        </a>
        {% endfor %}

        {% else %}

        {% for tag, count in tagRecords %}
        <a class="list-group-item {% if tagId == tag.id %}active{% endif %}">
            <span class="badge">{{ count }}</span>{{ tag.name }}
        </a>
        {% endfor %}

        {% endif %}
    </ul>
</div>
{% endblock extra %}


{% block main %}

{% if not pagination or not pagination.items %}

<div class="box-3d">
    <h5>没有任何文章哦。。。</h5>
</div>

{% else %}

{% for article in pagination.items %}
{{ renderArticleSimple(article) }}
{% endfor %}

<div>
    <center>
        {% if tagId %}
        {{ renderPagination(pagination, 'user.home', tagId=tagId, userId=user.id) }}
        {% else %}
        {{ renderPagination(pagination, 'user.home', userId=user.id) }}
        {% endif %}
    </center>
</div>

{% endif %}

{% endblock main %}

app/templates/user/setting.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros/utility.html" import renderFlashedMessages %}

{% block title %}设置{% endblock title %}

{% block content %}
<div class="container">

    {{ renderFlashedMessages('warning') }}

    <div class="box-3d">
        <div>
            <ul class="nav nav-tabs">
                <li role="presentation" {% if baseInfoForm %}class="active"{% endif %}>
                    <a href="{{ url_for('user.setBaseInfo') }}">基本设置</a>
                </li>
                <li role="presentation" {% if passwordForm %}class="active"{% endif %}>
                    <a href="{{ url_for('user.setPassword') }}">密码设置</a>
                </li>
            </ul>
        </div>

        <div>
            {% if baseInfoForm %}
            {{ wtf.quick_form(baseInfoForm) }}
            {% else %}
            {{ wtf.quick_form(passwordForm) }}
            {% endif %}
        </div>
    </div>

</div>
{% endblock content %}