app/main/views.py
from flask import (render_template, Blueprint, current_app, request, abort)
from flask_login import login_required, current_user
from sqlalchemy import desc, func, and_
from .logger import logger
from ..models import Article, Tag, ArticleTag, db, User, Following
from ..utility import exceptionHandler


main = Blueprint('main', __name__, template_folder="templates")


@main.route('/')
@exceptionHandler(logger, 'failed to visit homepage')
def index():
    pageNoStr = request.args.get('pageNo')
    pageNo = int(pageNoStr) if pageNoStr else 1
    pagination = (Article.query.filter(Article.deleted == False).
                  order_by(desc(Article.creationDate)).
                  paginate(pageNo,
                           current_app.config['ARTICLE_COUNT_PER_PAGE'],
                           False))
    return render_template('main/index.html', pagination=pagination,
                           hotTagRecords=Tag.
                           getHotTagRecords(current_app.config['HOT_TAG_COUNT']))


@main.route('/subscriptions')
@login_required
@exceptionHandler(logger, "failed to get subscriptions")
def subscriptions():
    # subscription 订阅
    try:
        pageNo = int(request.args.get('pageNo') or 1)
    except:
        abort(400)

    followedUserIdsQuery = (db.session.query(Following.userId).
                            filter(Following.followerId == current_user.id))
    followedCount = followedUserIdsQuery.count()

    pagination = None
    if followedCount:
        pagination = (db.session.query(Article).
                      filter(and_(Article.deleted == False,
                                  Article.userId.in_(followedUserIdsQuery))).
                      order_by(desc(Article.creationDate)).
                      paginate(pageNo,
                               current_app.config['ARTICLE_COUNT_PER_PAGE'],
                               False))
    return render_template('main/subscriptions.html',
                           followedCount=followedCount,
                           pagination=pagination)


@main.route('/concernedTags')
@login_required
@exceptionHandler(logger, 'failed to visit /concernedTags')
def concernedTags():
    concernedTags = current_user.concernedTags.all()
    if concernedTags:
        try:
            tagId = int(request.args.get('tagId') or concernedTags[0].id)
            pageNo = int(request.args.get('pageNo') or 1)
            if tagId not in (tag.id for tag in concernedTags):
                raise ValueError("{} didn't concerned tag {}".
                                 format(current_user, tagId))
        except:
            abort(400)

    stmt = Tag.query.get(tagId).articleRecords.subquery()
    pagination = (Article.query.filter(Article.deleted == False).
                  join(stmt, stmt.c.articleId == Article.id).
                  order_by(desc(Article.creationDate)).
                  paginate(pageNo,
                           current_app.config['ARTICLE_COUNT_PER_PAGE'],
                           False))

    return render_template('main/concernedTags.html', currentTagId=tagId,
                           concernedTags=concernedTags, pagination=pagination)


@main.route('/showTag/<int:tagId>')
@exceptionHandler(logger, 'failed to show tag')
def showTag(tagId):
    tag = Tag.query.get_or_404(tagId)
    try:
        pageNo = int(request.args.get('pageNo') or 1)
    except:
        abort(400)

    order = (desc(Article.viewedCount) if request.args.get('hot')
             else desc(Article.creationDate))

    articleIdsQuery = (db.session.query(ArticleTag.articleId).
                       filter(ArticleTag.tagId == tag.id).subquery())
    pagination = (Article.query.filter(Article.deleted == False).
                  join(articleIdsQuery, Article.id == articleIdsQuery.c.articleId).
                  order_by(order).order_by(desc(Article.creationDate)).
                  paginate(pageNo, current_app.config['ARTICLE_COUNT_PER_PAGE']))

    stmt = db.session.query(ArticleTag.articleId).filter(ArticleTag.tagId == tag.id).subquery()
    stmt2 = (db.session.query(Article.userId, func.count(Article.id).label('count')).
             filter(Article.deleted == False).
             join(stmt, stmt.c.articleId == Article.id).
             group_by(Article.userId).order_by(desc(func.count(Article.id))).
             limit(current_app.config['FAMOUS_USER_COUNT'])).subquery()
    famousUserRecords = (db.session.query(User, stmt2.c.count).
                         join(stmt2, User.id == stmt2.c.userId).
                         order_by(desc(stmt2.c.count)).all())

    return render_template('main/showTag.html', tag=tag,
                           pagination=pagination,
                           famousUserRecords=famousUserRecords)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <!-- 这三个meta标签必需放在最前面 -->
    <meta charset="utf-8" />
    <meta charset="X-UA-Compatible" content="IE=edge" />
    <meta name="Viewport" content="width=device-width, initial-scale=1" />

    {% block css %}
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}", rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet"/>
    {% endblock css %}

    {% block js %}
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% endblock js %}

    <title>{% block title %}base{% endblock title %}</title>
</head>

{% block body %}
<body class="gray-background">
    {% block nav %}
    <nav class="navbar navbar-static-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Blog</a>
            </div>

            <div class="collapse navbar-collapse">
                <form id="top-navbar-search-form" class="navbar-form navbar-left">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="搜索您感兴趣的内容" />
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>

                <ul class="nav navbar-nav">
                    <li {% block homeActived %}{% endblock homeActived %}><a href="{{ url_for('main.index') }}">首页</a></li>
                    <li {% block subscriptionsActived %}{% endblock subscriptionsActived %}><a href="{{ url_for('main.subscriptions') }}">关注</a></li>
                    <li {% block themeActived %}{% endblock themeActived %}><a href="{{ url_for('main.concernedTags') }}">主题</a></li>
                </ul>

                <!-- 在用户登陆后 -->
                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="flase">{{ current_user.name }}</a>
                        <ul class="dropdown-menu">
                            <li><a href="#">个人主页</a></li>
                            <li><a href="#">设置</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                        </ul>
                    </li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                </ul>
                {% endif %}

            </div>

        </div>
    </nav>
    {% endblock nav %}

    {% block content %}
    <div class="container">
        <h2>base</h2>
    </div>
    {% endblock content %}
</body>
{% endblock body %}

</html>

app/templates/layoutExtraLeft.html
{% extends "base.html" %}


{% block content %}

<div class="container">

    <div id="left-extra" class="col-sm-3">
        {% block extra %}
        {% endblock extra %}
    </div>

    <div id="right-main" class="col-sm-9">
        {% block main %}
        {% endblock main %}
    </div>

</div>

{% endblock content %}

app/templates/layoutMainLeft.html
{% extends "base.html" %}
{% from "macros/utility.html" import renderFlashedMessages %}


{% block content %}

<div class="container">

    {% block top %}
    {{ renderFlashedMessages('warning') }}
    {% endblock %}

    <div id="left-main" class="col-sm-9">
        {% block main %}
        {% endblock main %}
    </div>

    <div id="right-extra" class="col-sm-3">
        {% block extra %}
        {% endblock extra %}
    </div>

</div>

{% endblock content %}